name: "CI"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying using ssh
    steps:
      -run: |
        echo ${{ secrets.ORACLE_SSH_PVT_KEY }} &> ~/ssh_key
        mkdir .ssh
        echo ${{ secrets.KNOWN_HOSTS }} &> ~/.ssh/known_hosts
        ssh -i ~/ssh_key ubuntu@${{ secrets.ORACLE_SSH_IP }}
        cd LocalTodo && git pull && pnpm install && pnpm build
        pm2 restart all

